### ISSUE TITLE
Клиент лагает если долго не обновлять страничку

### ISSUE THREAD

**Issue by GlebkaF** [Crazymax11/simple-chat#11]
Сообщения отправляются секунды по 3.

**Comment by Crazymax11** [comment]
titleTimeout = setInterval(function(){
            $("title").html(msg2);
            $('link[rel$=icon]').remove();
            $('head').append( $('<link rel="shortcut icon" type="image/x-icon"/>' ).attr( 'href', "images/ico/" + icon2  ) );
        },1000)

данный код выполняется бесконечно, что и является причиной лагов

**Comment by Crazymax11** [comment]
не повторяется более
