### ISSUE TITLE
Доделка интерфейса

### ISSUE THREAD

**Issue by Crazymax11** [Crazymax11/simple-chat#3]
инпут 2 кнопки и 2 белых дива это @#$%^&*ец
Нужны нормальные колонки, нормальные бордеры и бэкграунды
ориентируемся на темный интерфейс + возможность расширения на другие цвета (темы)

**Comment by GlebkaF** [comment]
![proto](https://cloud.githubusercontent.com/assets/8992139/13905070/3d4f5aae-eedf-11e5-8cdd-3829e1c3bddb.png)

**Comment by GlebkaF** [comment]
![image](https://cloud.githubusercontent.com/assets/8992139/13905817/97782028-eef4-11e5-9570-f807f5de6af0.png)

**Comment by GlebkaF** [comment]
D182f724d44d0bd7fba6b51d9218a9f8853c44677

**Comment by GlebkaF** [comment]
Сделано в 182f724d44d0bd7fba6b51d9218a9f8853c44677
