### ISSUE TITLE
Запретить повторяющиеся никнеймы

### ISSUE THREAD

**Issue by Crazymax11** [Crazymax11/simple-chat#7]
сервер на попытку залогинится под чужим никнейном генерирует новый рандомный,с ним и живи, повторюша

**Comment by GlebkaF** [comment]
Хотел такую ишую открыть, а она уже открыта :cry:

**Comment by Crazymax11** [comment]
сделано в c46a77e724faee6062557d6ae31fa6a0b81f0f2f
